// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(SistemaTarefasDBContex))]
    partial class SistemaTarefasDBContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            // Configuração da entidade 'TarefaModel'
            modelBuilder.Entity("WebApplication1.Models.TarefaModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int?>("UsuarioId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UsuarioId");

                b.ToTable("Tarefas");
            });

            // Configuração da entidade 'UsuarioModel'
            modelBuilder.Entity("WebApplication1.Models.UsuarioModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("DataNascimento")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<string>("Endereco")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Sexo")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int>("Telefone")
                    .HasMaxLength(150)
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Usuarios");
            });

            // Configuração do relacionamento entre 'TarefaModel' e 'UsuarioModel'
            modelBuilder.Entity("WebApplication1.Models.TarefaModel", b =>
            {
                b.HasOne("WebApplication1.Models.UsuarioModel", "Usuario")
                    .WithMany()
                    .HasForeignKey("UsuarioId");

                b.Navigation("Usuario");
            });
#pragma warning restore 612, 618
        }
    }
}